[build-system]
requires = [
  "setuptools>=68",
  "wheel>=0.41",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [""]
include = ["amclient*"]
namespaces = false

[project]
name = "amclient"
dynamic = [
  "version",
  "readme",
]
description = "Archivematica API client library."
requires-python = ">=3.8"
license = {file = "LICENSE"}
dependencies = [
  "requests",
  "urllib3",
]
keywords = [
  "archivematica",
  "preservation",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: GNU Affero General Public License v3",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
authors = [
  {name = "Artefactual Systems Inc.", email = "info@artefactual.com"}
]
maintainers = [
  {name = "Artefactual Systems Inc.", email = "info@artefactual.com"}
]

[project.urls]
homepage = "https://github.com/artefactual-labs/amclient/"
repository = "https://github.com/artefactual-labs/amclient/"
issues = "https://github.com/archivematica/Issues/issues"

[project.scripts]
amclient = "amclient.amclient:main"

[project.optional-dependencies]
dev = [
  "coverage",
  "pip-tools",
  "pytest-cov",
  "pytest",
]

[tool.setuptools.dynamic]
version = {attr = "amclient.version.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.pytest.ini_options]
python_files = [
  "test_*.py",
]
testpaths = [
  "tests",
]

[tool.coverage.run]
source = [
  "amclient",
]
branch = true
omit = [
  "tests/*",
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist = py{38,39,310,311,312}, linting

    [gh-actions]
    python =
        3.8: py38
        3.9: py39
        3.10: py310
        3.11: py311
        3.12: py312

    [testenv]
    skip_install = true
    deps = -r {toxinidir}/requirements-dev.txt
    commands =  pytest {posargs}

    [testenv:linting]
    basepython = python3
    deps = pre-commit
    commands = pre-commit run --all-files --show-diff-on-failure
"""
